name: Build Debug

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: '17.6' # Visual Studio 2022 version 17.6
        include-vcbuild: true

    - name: Install .NET 6 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install COSMOS Dev Kit (1/2)
      run: |
        git clone https://github.com/CosmosOS/Cosmos.git --depth 1
        cd Cosmos
        dir
      shell: pwsh
    
    - name: Install COSMOS Dev Kit (2/2)
      run: |
          cd D:\a\VivDOS-NET\VivDOS-NET\Cosmos
          install-VS2022.cmd
      shell: cmd

    - name: Restore NuGet packages
      run: nuget restore VivDOS.sln
      shell: pwsh

    - name: Check directory
      run: dir

#    - name: Build the COSMOS Kernel
#      run: dotnet build --configuration Release
#      shell: pwsh

    - name: Build solution
      run: msbuild /p:Configuration=Release VivDOS.sln